/* typedef enum { */
/*   ARM_REG_MIDR_ACC_IMP, */
/*   ARM_REG_MIDR_ACC_VAR, */
/*   ARM_REG_MIDR_ACC_ARCH, */
/*   ARM_REG_MIDR_ACC_PRIM, */
/*   ARM_REG_MIDR_ACC_REV */
/* } ARM_REG_MIDR_ACCESS_TYPE; */

typedef enum {
  ARM_REG_MIDR_IMP_ARM      = 0x41,
  ARM_REG_MIDR_IMP_DEC      = 0x44,
  ARM_REG_MIDR_IMP_MOTOROLA = 0x4D,
  ARM_REG_MIDR_IMP_QUALCOMM = 0x51,
  ARM_REG_MIDR_IMP_MARVELL  = 0x56,
  ARM_REG_MIDR_IMP_INTEL    = 0x69
} ARM_REG_MIDR_IMP_ENUM;

typedef enum {
  ARM_REG_MIDR_ARCH_V4     = 0x1,
  ARM_REG_MIDR_ARCH_V4T    = 0x2,
  ARM_REG_MIDR_ARCH_V5     = 0x3,
  ARM_REG_MIDR_ARCH_V5T    = 0x4,
  ARM_REG_MIDR_ARCH_V5TE   = 0x5,
  ARM_REG_MIDR_ARCH_V5TEJ  = 0x6,
  ARM_REG_MIDR_ARCH_V6     = 0x7,
  ARM_REG_MIDR_ARCH_CPUID  = 0xF
} ARM_REG_MIDR_ARCH_ENUM;

extern const UINT16 ARM_REG_MIDR_PRIM_ALT_ENC_MASK;

extern const UINT16 ARM_REG_MIDR_METADATA_ALT_ENC;

typedef struct {
  ARM_REG_MIDR_IMP_ENUM ARM_REG_MIDR_IMP;
  UINT8 ARM_REG_MIDR_VAR;
  ARM_REG_MIDR_ARCH_ENUM ARM_REG_MIDR_ARCH;
  UINT16 ARM_REG_MIDR_PRIM;
  UINT8 ARM_REG_MIDR_REV;
  UINT16 metadata;
} ARM_REG_MIDR_SUMMARY;

ARM_REG_MIDR_SUMMARY ArmRegMidrSummary();
