[LibraryClasses.common]
  BaseLib|                  MdePkg/Library/BaseLib/BaseLib.inf
  DebugLib|                 MdePkg/Library/BaseDebugLibNull/BaseDebugLibNull.inf
  DebugAgentLib|            MdeModulePkg/Library/DebugAgentLibNull/DebugAgentLibNull.inf
  IoLib|                    MdePkg/Library/BaseIoLibIntrinsic/BaseIoLibIntrinsic.inf
  PrintLib|                 MdePkg/Library/BasePrintLib/BasePrintLib.inf
  SerialPortLib|            MdePkg/Library/BaseSerialPortLibNull/BaseSerialPortLibNull.inf
  CacheMaintenanceLib|      MdePkg/Library/BaseCacheMaintenanceLibNull/BaseCacheMaintenanceLibNull.inf


[LibraryClasses.Arm]
  ArmLib|                   ArmPkg/Library/ArmLib/ArmBaseLib.inf
  # ?
  ArmPlatformLib|           ArmPlatformPkg/Library/ArmPlatformLibNull/ArmPlatformLibNull.inf
  # PrePeiCoreUniCore|        ArmPlatformPkg/PrePeiCore/PrePeiCoreUniCore.inf